config/routes.rb
Rails.application.routes.draw do

  resources :flashcards
  resources :clients
  devise_for :users

  root 'pages#home'
  get 'pages/about'
  get 'pages/index'
  get 'pages/test'
  get 'pages/doors_and_windows'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/flashcard.rb
class Flashcard < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:lead_status, :lead_source, :project_address, :phone_number, :email, :type_of_project, :payment_method)
    end
end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
  before_action :set_flashcard, only: [:show, :edit, :update, :destroy]

  # GET /flashcards
  # GET /flashcards.json
  def index
    @flashcards = Flashcard.all
  end

  # GET /flashcards/1
  # GET /flashcards/1.json
  def show
  end

  # GET /flashcards/new
  def new
    @flashcard = Flashcard.new
  end

  # GET /flashcards/1/edit
  def edit
  end

  # POST /flashcards
  # POST /flashcards.json
  def create
    @flashcard = Flashcard.new(flashcard_params)

    respond_to do |format|
      if @flashcard.save
        format.html { redirect_to @flashcard, notice: 'Flashcard was successfully created.' }
        format.json { render :show, status: :created, location: @flashcard }
      else
        format.html { render :new }
        format.json { render json: @flashcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flashcards/1
  # PATCH/PUT /flashcards/1.json
  def update
    respond_to do |format|
      if @flashcard.update(flashcard_params)
        format.html { redirect_to @flashcard, notice: 'Flashcard was successfully updated.' }
        format.json { render :show, status: :ok, location: @flashcard }
      else
        format.html { render :edit }
        format.json { render json: @flashcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flashcards/1
  # DELETE /flashcards/1.json
  def destroy
    @flashcard.destroy
    respond_to do |format|
      format.html { redirect_to flashcards_url, notice: 'Flashcard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flashcard
      @flashcard = Flashcard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flashcard_params
      params.require(:flashcard).permit(:title, :description, :img_url)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @hide_back_button = true #Hides back button on app.html.erb
  end

  def doors_and_windows

  end

  def about
  end

  def index
  end

  def test
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/flashcards_helper.rb
module FlashcardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lead_status %>
    <%= form.text_field :lead_status %>
  </div>

  <div class="field">
    <%= form.label :lead_source %>
    <%= form.text_field :lead_source %>
  </div>

  <div class="field">
    <%= form.label :project_address %>
    <%= form.text_field :project_address %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.number_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :type_of_project %>
    <%= form.text_field :type_of_project %>
  </div>

  <div class="field">
    <%= form.label :payment_method %>
    <%= form.text_field :payment_method %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Lead status</th>
      <th>Lead source</th>
      <th>Project address</th>
      <th>Phone number</th>
      <th>Email</th>
      <th>Type of project</th>
      <th>Payment method</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.lead_status %></td>
        <td><%= client.lead_source %></td>
        <td><%= client.project_address %></td>
        <td><%= client.phone_number %></td>
        <td><%= client.email %></td>
        <td><%= client.type_of_project %></td>
        <td><%= client.payment_method %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lead status:</strong>
  <%= @client.lead_status %>
</p>

<p>
  <strong>Lead source:</strong>
  <%= @client.lead_source %>
</p>

<p>
  <strong>Project address:</strong>
  <%= @client.project_address %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @client.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Type of project:</strong>
  <%= @client.type_of_project %>
</p>

<p>
  <strong>Payment method:</strong>
  <%= @client.payment_method %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/flashcards/_form.html.erb
<%= form_with(model: flashcard, local: true) do |form| %>
  <% if flashcard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flashcard.errors.count, "error") %> prohibited this flashcard from being saved:</h2>

      <ul>
        <% flashcard.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :img_url %>
    <%= form.text_field :img_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flashcards/edit.html.erb
<h1>Editing Flashcard</h1>

<%= render 'form', flashcard: @flashcard %>

<%= link_to 'Show', @flashcard %> |
<%= link_to 'Back', flashcards_path %>

app/views/flashcards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flashcards</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Img url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flashcards.each do |flashcard| %>
      <tr>
        <td><%= flashcard.title %></td>
        <td><%= flashcard.description %></td>
        <td><%= flashcard.img_url %></td>
        <td><%= link_to 'Show', flashcard %></td>
        <td><%= link_to 'Edit', edit_flashcard_path(flashcard) %></td>
        <td><%= link_to 'Destroy', flashcard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flashcard', new_flashcard_path %>

app/views/flashcards/new.html.erb
<h1>New Flashcard</h1>

<%= render 'form', flashcard: @flashcard %>

<%= link_to 'Back', flashcards_path %>

app/views/flashcards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @flashcard.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @flashcard.description %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @flashcard.img_url %>
</p>

<%= link_to 'Edit', edit_flashcard_path(@flashcard) %> |
<%= link_to 'Back', flashcards_path %>

app/views/layouts/_nav.html.erb
<!-- <nav class="navbar navbar-expand-lg navbar-dark bg-light"> -->

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <li class="navbar-brand">
      <%= link_to  "General Contracting", root_path, class:"navbar-brand" %>
    </li>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
<!-- Nav Left -->
      <ul class="navbar-nav mr-auto">

        <li class="nav-item">
          <%= link_to "Test Page", pages_test_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Index", pages_index_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Flashcards", flashcards_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Doors and Windows", pages_doors_and_windows_path, class:"nav-link" %>
        </li>

      </ul>

      <hr>
<!-- Nav Right -->
      <ul class="navbar-nav ml-auto">

          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to "About", pages_about_path, class:"nav-link" %>
            </li>

            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "Account Settings", edit_user_registration_path, class:"nav-link" %>
              </li>
              <li class="nav-item">

                <%= link_to 'Sign out', destroy_user_session_path, :method => :delete, class:"nav-item nav-link" %>

                <%#= link_to 'Logout', destroy_user_session_path, method: :delete, class:"nav-item nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Sign In",  new_user_session_path, class:"nav-link"   %>
              </li>
              <li class="nav-item">
                <%= link_to "Register",   new_user_registration_path, class:"nav-link"   %>
              </li>
            <% end %>






          </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- <title>SpotStop</title> -->

    <% if @page_title.present? %>
      <title>General Contracting App | <%= "#{@page_title}"%></title>
    <% else %>
      <title>General Contracting App</title>
    <% end %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  </head>

  <body class="bg-indigo-100">


      <%= render "layouts/nav" %>

      <% if notice.present? || alert.present? %>
        <div id="fadeAway" class="text-center">
          <br>
          <br>
          <p class="notice" id="notice" style="color:green; font-size:200%;">
            <%= notice %>
          </p>
          <p class="alert" id="alert" style="color:red; font-size:200%;">
            <%= alert %>
          </p>
        </div>
      <% end %>

      <span class="pl-4">
        <% if user_signed_in? %>
            <%= link_to "Welcome #{current_user.email}", root_path %>
        <% end %>
      </span>

      <div class="py-5 p-2">
          <div class="card container p-4">
          <br>
          <%= yield %>
          </div>
            <div class="text-center">
              <br>
            <% if @hide_back_button != true %>
            <%= link_to 'Back', :back, class:"btn btn-primary", style: 'color:#FFFFFF;' %>
            <% end %>

            </div>
      </div>

  </body>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>


  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<!-- Fade out Notice and Alert -->
  <script type="text/javascript">
    $( "#fadeAway" ).delay(1000).fadeOut( "slow", function() {
    });
  </script>


</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/doors_and_windows.html.erb
<h1>Pages#doors_and_windows</h1>

<hr>

<h1 class="display-4">Doors</h1>
<hr>


<!-- <div class="border-solid border-6">
  <p>Click the "Try it" button to toggle between hiding and showing the DIV element:</p>

  <button onclick="myFunction()">Try it</button>

  <div id="myDIV" class="border-solid">
    <h1>Showing</h1>
  </div>

  <p><b>Note:</b> The element will not take up any space when the display property set to "none".</p>
</div> -->

<div>
  <span>

    <span>
      <img src="https://impactglass.net/wp-content/uploads/2019/05/iconos-puertas_0001_Capa-4.png" alt="">

      <p id="door-1" class="display-4" style="font-size:150%;">Pivot Door</p>

    </span>

    <span>
      <img src="https://impactglass.net/wp-content/uploads/2019/05/iconos-puertas_0000_Capa-5.png" alt="">
      <p  id="door-2" class="display-4" style="font-size:150%;">Bi-Fold Door</p>
    </span>

    <span>
      <img src="https://impactglass.net/wp-content/uploads/2019/05/iconos-puertas_0004_Capa-1.png" alt="">
      <p  id="door-3" class="display-4" style="font-size:150%;">French Door</p>
    </span>

    <span>
      <img src="https://impactglass.net/wp-content/uploads/2019/07/iconos-puertas_0003_Capa-211.png" alt="">
      <p  id="door-4" class="display-4" style="font-size:150%;">Sliding Glass Door</p>
    </span>

    <span>
      <img src="https://impactglass.net/wp-content/euploads/2019/06/iconos-ventanas-nuevos_0001_Capa-31.png" alt="">
      <p   id="door-5" class="display-4" style="font-size:150%;"> Casement Window</p>
    </span>

    <span>
      <img src="https://impactglass.net/wp-content/uploads/2019/07/iconos-puertas_0003_Capa-21.png" alt="">
      <p  id="door-6" class="display-4" style="font-size:150%;"> Horizontal sliding Window</p>
    </span>

    <span>
      <img src="https://impactglass.net/wp-content/uploads/2019/05/iconos-ventanas-nuevos_0001_Capa-3.png" alt="">
      <p   id="door-7" class="display-4" style="font-size:150%;">Single Hung</p>
    </span>

    <span>
      <img src="https://impactglass.net/wp-content/uploads/2019/05/iconos-ventanas-nuevos_0000_Capa-4.png" alt="">
      <p  id="door-8" class="display-4" style="font-size:150%;">Fixed Window</p>
    </span>


  </span>
</div>

<script>


// function myFunction() {
//   var x = document.getElementById("myDIV");
//   if (x.style.display === "block") {
//     x.style.display = "none";
//   } else {
//     x.style.display = "none";
//   }
// }


  // for (let step = 0; step < 5; step++) {
  //   // Runs 5 times, with values of step 0 through 4.
  //   alert(`Step number ${step}`);
  // }


    // var i;
    // for (i = 0; i < 8; i++) {
    //   }

  // var x = document.getElementById("myDIV");
  //   if (x.style.display === "none") {
  //     x.style.display = "block";
  //   } else {
  //     x.style.display = "none";
  //   }
  // }




</script>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<hr>

<h1>Windows</h1>
<h2>Why do People Replace Windows?</h2>
<p>Efficency, old, saftey reasons(safety for family), home value(add equity), beauty.</p>

<h1>Companies:</h1>

<h1> Low E glass = Tinted glass </h1>

Barrel, archetechtual, flat

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/test.html.erb
<h1>Pages#Test</h1>
<hr>

<h2> Client Attributes: </h2>
<p> Lead Status- Cold, Warm, Hot</p>
<p>Lead Source</p>
<p>Project Address</p>
<p>Phone number</p>
<p>Email</p>
<p>Type of Project</p>
<p>Contractor For Project</p>
<p>Method of Payment</p>

<hr>

<h2> Appointment: </h2>
<p>Time of Appointment</p>
<p>Appointment Status</p>
<p>First Appointment time/date</p>
<p>last check-in (last time there)</p>
<p>On Site Technition</p>

<hr>

<h2> Company: </h2>
<p> Company Title ex) AA Glass/Care Construction/Custom/FHI- Florida Homeowner Improvement </p>
<p>Job Type</p>
<p>Company Phone</p>
<p>Company Email</p>
<p>Company address</p>
<p> Employee </p>
<p> Employee Title </p>
<p>Employee Phone Number</p>
<p>Employee Email</p>

<hr>

<h2>Automate Emails</h2>

<hr>

<h2>Contract:</h2>
<p>Company </p>
<p>Client (First/Last Name, Address, Phone Number)</p>
<p>Breakdown</p>
<p>Price</p>

<h2>Calculator:</h2>
<p>  Seperate calc page </p>
<p>calc can be general or belong to client</p>

<hr>

<h2>Reminders:</h2>
<p>  </p>

<hr>